export const elements = {
    container: document.querySelector('.container'),
    searchForm: document.querySelector('.search'),
    searchInput: document.querySelector('.search__input'),
    searchResults: document.querySelector('.search__results'),
    searchResultsItem: document.querySelector('.search__results__item'),
    card: document.querySelector('.card'),
    cardPlaceName: document.querySelector('.card__place-name'),
    cardTemp: document.querySelector('.card__temp'),
    cardIcon: document.querySelector('.card__icon'),
    cardNextFive: document.querySelector('.card__next-five'),
    nextFiveList: document.querySelector('.card__next-five__list'),
    menuIcon: document.querySelector('.search__menu-icon'),
    menu: document.querySelector('.menu'),
    menuClose: document.querySelector('.menu__close'),
    mainTemp: document.querySelector('.card__temp--main'),
    mainHiLo: document.querySelector('.card__temp--hi-lo'),
    nextFiveMainTemp: document.querySelector('.card__next-five__list-item__temp--main'),
    nextFiveHiLo: document.querySelector('.card__next-five__list-item__temp--hi-lo')
};
